function Mario(game,x,y,name)
{
    this._x=x;
    this._y=y;
    this._life=3;
    this._velocity=1;
    this._jumpHeight=2;
    Phaser.Sprite.call(this,game,x,y,name);
}
Mario.prototype=Object.create(Phaser.Sprite.prototype);
Mario.constructor=Mario;

Mario.prototype.Move=function(dir)
{
    this._x+=dir*this._velocity;
}
Mario.prototype.Jump=function()
{
    this._y-=this._jumpHeight;
}
Mario.prototype.Die=function()
{
    console.log("Muerto");
}
Mario.prototype.Hurt=function()
{
    if(this._life>1)
    this._life--;
    else
    Mario.Muerto();
}
module.exports=Mario;
